// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blqccpfpmuwlcrcoscpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJscWNjcGZwbXV3bGNyY29zY3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjE0NzgsImV4cCI6MjA2NDAzNzQ3OH0.Zk6vQf3alGXuC7QjMtPGB6GYYQHTbfWE6hHWm9odLmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);